import Sprockell

prog :: [Instruction]
prog = [ 
       Load (ImmValue 2) regA, 
       Push regA, 
       Pop regA, 
       Store regA (DirAddr 0), 
       Load (DirAddr 0) regA, 
       Push regA, 
       Load (ImmValue 12) regA, 
       Push regA, 
       Pop regB, 
       Pop regA, 
       Compute Lt regA regB regA, 
       Push regA, 
       Pop regA, 
       Branch regA (Rel 2), 
       Jump (Rel 12), 
       Load (DirAddr 0) regA, 
       Push regA, 
       Load (ImmValue 1) regA, 
       Push regA, 
       Pop regB, 
       Pop regA, 
       Compute Add regA regB regA, 
       Push regA, 
       Pop regA, 
       Store regA (DirAddr 0), 
       Jump (Rel (-21)), 
       Load (DirAddr 0) regA, 
       Push regA, 
       Load (ImmValue 0) regA, 
       Push regA, 
       Pop regB, 
       Pop regA, 
       Compute Gt regA regB regA, 
       Push regA, 
       Pop regA, 
       Branch regA (Rel 2), 
       Jump (Rel 12), 
       Load (DirAddr 0) regA, 
       Push regA, 
       Load (ImmValue 1) regA, 
       Push regA, 
       Pop regB, 
       Pop regA, 
       Compute Sub regA regB regA, 
       Push regA, 
       Pop regA, 
       Store regA (DirAddr 0), 
       Jump (Rel (-21)), 
       Load (DirAddr 0) regA, 
       Push regA, 
       Pop regA, 
       WriteInstr regA numberIO, 
       EndProg
       ]

main = run [prog]